{% if theme.cnzz_siteid %}
	
    <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan style='position: absolute;float:left;top: 20px;' id='cnzz_stat_icon_{{ theme.cnzz_siteid }}'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s22.cnzz.com/z_stat.php%3Fid%3D{{ theme.cnzz_siteid }}%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>

{% endif %}