[[Main]]
  Name = "Home"
  Pre = "home"
  URL = "/en/"
  Weight = 1
[[Main]]
  Name = "Archive"
  Pre = "archive"
  URL = "/en/post/"
  Weight = 2
[[Main]]
  Name = "About"
  Pre = "user"
  URL = "/en/about/"
  Weight = 3
[[Main]]
  Name = "Page404"
  Pre = "heartbeat"
  URL = "/404.html"
  Weight = 4