jobs:
  include:
  - stage: One
    os: linux
    dist: focal
language: go
go:
- 1.12.1
git:
  submodules: false
branches:
  only:
  - hugo
env:
- HUGO_VERSION=0.87.0
before_install:
- openssl aes-256-cbc -K $encrypted_616d5dfb4ec4_key -iv $encrypted_616d5dfb4ec4_iv
  -in .travis/id_rsa_travis.enc -out ~/.ssh/id_rsa -d
- ssh-keyscan $TENCENT_CLOUD_SER >> ~/.ssh/known_hosts
- chmod 600 ~/.ssh/id_rsa
- export TZ='Asia/Shanghai'
- export LANG="zh_CN.UTF-8"
install:
- wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  -nd -P soft
- tar -xzvf soft/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz -C soft
- chmod +x soft/hugo
- export PATH=$PATH:$PWD/soft
- hugo version
- echo 'Hugo engine env is ready.'
script:
- git submodule update --init --recursive
- rm -rf public
- sh .travis/replace_params_value.sh
- hugo -t hugo-theme-next -d public/
before_deploy:
- cp README.md ./public/README.md
- cp README.zh.md ./public/README.zh.md
- cp LICENSE ./public/LICENSE
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: main
  github-token: "$GITHUB_PAGES"
  fqdn: lisenhui.cn
  keep-history: true
  commit_message: Update blog site by TravisCI with build $TRAVIS_BUILD_ID
  on:
    branch: hugo
after_deploy:
- pwd
- ls -al
- echo "Deploy blog article success."
- echo "Deploy to Tencent cloud server."
- ssh -i ~/.ssh/id_rsa lighthouse@$TENCENT_CLOUD_SER "sh ~/deploy.sh >> ~/deploy.log"
- echo "Deploy to Tencent cloud server successfully."
