language: go
sudo: required

branches:
  only:
    - hugo

cache:
  directories:
    - themes

addons:
  ssh_known_hosts:
    - github.com

before_install:
  - export TZ='Asia/Shanghai'
  - git config --global user.email "elkan1788@gmail.com"
  - git config --global user.name "凡梦星尘"
  - export LANG="zh_CN.UTF-8"


install:  
  - wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.80.0_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version  
  - echo 'Hugo engine env is ready!'
  - ls -al
  - pwd
 
 deploy:
  provider: script
  script: sh .travis/deploy.sh 
  on:
    branch: hugo


script:
  - echo 'Deploy blog site success.'