language: go

sudo: required

branches:
  only:
    - hugo

cache:
  directories:
    - themes

addons:
  ssh_known_hosts:
    - github.com

env:
  - HUGO_VERSION=0.80.0

before_install:
  - export TZ='Asia/Shanghai'
  - export LANG="zh_CN.UTF-8"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - tar -xzvf hugo_${HUGO_VERSION}_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version  
  - echo 'Hugo engine env is ready.'

script:
  - hugo -t NexT

before_deploy:
  - pwd
  - ls -al 
  - cat ./README.md
  - cat ./themes/NexT/README.md

#  - cp -r LICENSE ./public
#  - cp -r .gitignore ./public
#  - cp -r themes/NexT/README.md ./public

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: main
  github-token: $GITHUB_PAGES
  fqdn: lisenhui.cn
  keep-history: true
  commit_message: "Update blog site by TravisCI with build $TRAVIS_BUILD_ID"
  on:
    branch: hugo

after_deploy:    
  - pwd
  - ls -al 
  - ls -al ./public
  - echo $(travis_build_id)