language: go
sudo: required

branches:
  only:
    - hugo

cache:
  directories:
    - themes

addons:
  ssh_known_hosts:
    - github.com

before_install:
  - export TZ='Asia/Shanghai'
  - export LANG="zh_CN.UTF-8"

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.80.0/hugo_0.80.0_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.80.0_Linux-64bit.tar.gz
  - chmod +x hugo
  - export PATH=$PATH:$PWD
  - hugo version  
  - echo 'Hugo engine env is ready.'

script:
  - hugo -t NexT  
  - pwd
  - ls -al
  - cat README.md
  - cp LICENSE ./public
  - cp .gitignore ./public

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: main
  github-token: $GITHUB_PAGES
  fqdn: lisenhui.cn
  keep-history: true
  commit_message: "Update blog site by TravisCI with build $TRAVIS_BUILD_NUMBER"
  on:
    branch: hugo

after_script:
  - echo 'Deploy blog site success.'