Title =  "Loving life and dreams."
LanguageCode = "zh-CN"
Theme =  "hugo-theme-next"

MetaDataFormat =  "toml"

PaginatePath =  "p"
Paginate = 10

DisablePathToLower =  false
PreserveTaxonomyNames = false

PygmentsStyle = "emacs"
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

DefaultContentLanguage = "zh"

enableRobotsTXT = true

[sitemap]
  filename = "sitemap.xml"
  changefreq = "weekly"
  priority = 0.5

[Permalinks]
  post = "/:year/:month/:day/:slug"


[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = true