{#
Custom head.
#}
<script>(function(i,s,o,g,r,a,m){i["DaoVoiceObject"]=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;a.charset="utf-8";m.parentNode.insertBefore(a,m)})(window,document,"script",('https:' == document.location.protocol ? 'https:' : 'http:') + "//widget.daovoice.io/widget/f89653b8.js","daovoice");daovoice('init',{app_id:"f89653b8"});daovoice('update');</script>
<script data-ad-client="ca-pub-9690092997324651" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
